name: Frontend CD

on:
  push:
    branches:
      - main
    paths:
      - "starter/frontend/**"
      - ".github/workflows/frontend_cd.yaml"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build frontend image
        working-directory: starter/frontend
        run: |
          docker build -t frontend:latest .

      - name: Tag frontend image
        run: |
          docker tag frontend:latest \
            081162991116.dkr.ecr.us-east-1.amazonaws.com/frontend:latest

      - name: Push frontend image
        run: |
          docker push \
            081162991116.dkr.ecr.us-east-1.amazonaws.com/frontend:latest
